# Pandas Basic

Ref: Data Wrangling with Pandas Cheat Sheet \
Website http://pandas.pydata.org

In [23]:
import pandas as pd

## 1.1 Creating DataFrames

In [37]:
# Specify values for each column
df = pd.DataFrame({"a":[4,5,6],
                   "b":[7,8,9],
                   "c":[11,11,12]}, index = [1,2,3])
df

a  b   c
1  4  7  11
2  5  8  11
3  6  9  12

In [38]:
# Specify values for each row
df = pd.DataFrame([[4,7,10],[5,8,11],[6,9,12]], index = [1,2,3], columns = ["a","b","c"])
df

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [39]:
# Create DataFrame with MultiIndex
df = pd.DataFrame({"a":[4,5,6],"b":[7,8,9],"c":[10,11,12]},
                  index = pd.MultiIndex.from_tuples([('D',1),('D',2),('e',2)], names = ['N','v']))
df

a  b   c
N v          
D 1  4  7  10
  2  5  8  11
e 2  6  9  12

## 1.2 Method Chaining

In [43]:
df = (pd.melt(df)
      .rename(columns = {
              'variable':'var',
              'value':'val'})
      .query('val>=200')
     )
df

Empty DataFrame
Columns: [var, val]
Index: []

## 1.3 Reshaping Data
- Change layout, sorting, reindexing, renaming

# Numpy Basic

In [8]:
import numpy as np
import math

In [6]:
A = np.array([1,-1,-1,1]).reshape(2,2)

In [7]:
A

array([[ 1, -1],
       [-1,  1]])

In [20]:
eigenvalue, eigenvector = np.linalg.eig(A)

In [21]:
eigenvalue

array([2., 0.])

In [22]:
eigenvector

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])